### ISSUE TITLE
Reference Document

### ISSUE THREAD

**Issue by jackhumbert** [lakmeer/zbalermorna#2]
Is there a more up-to-date reference besides the 4th Edition v2 write-up ([link to Google Doc](https://drive.google.com/file/d/0B0aL1oAS_j4yZjZKa3ZYYUNUdnVZdHdEMW5pMGdJUQ/view))? I like the vowel shapes here, but they don't seem to exactly match what's described in that doc.

**Comment by lakmeer** [comment]
The reference hasn't been updated since the 5th edition font work ground to a halt. I am fairly committed to the new vowel shapes but unfortunately that doc is still for 4th edition.

**Comment by jackhumbert** [comment]
Ah, gotcha! Do you have any guidelines for valid shapes for those? I'm mainly interested in if carons would be accepted as breves, and the flexibility of the `oi` shape.

Are there any other notes about changes from the 4th edition? I'd be happy to help document those somewhere if you're interested in that.

**Comment by lakmeer** [comment]
I can tell you that a caron (ˇ) would not read as a breve (˘). Corners and curves are not interchangeable. Corners may be loopy, but must retain a sharp intersection of strokes.

That may also answer your questions for `oi`, but feel free to email me at lakmeerkravid at gmail, if you have specific questions. It's much easier to discuss with images :)

**Comment by jackhumbert** [comment]
Great! Will do :) Thanks!

**Comment by lagleki** [comment]
Please don't change UTF space once a new versin is out. My scripts depend
on the current mapping.

Em qui, 25 de jul de 2019 às 05:32, lakmeer <notifications@github.com>
escreveu:
